# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TXT2TIF
                                 A QGIS plugin
 G空間情報センター等でダウンロードできるtxt形式のDEMをgeotiff形式に変換するプラグインです。
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-10
        copyright            : (C) 2025 by Mizuki TAKIGAWA
        email                : takigawa.mizuki011124@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TXT2TIF class from file TXT2TIF.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .txt_2_tif_dem_builder import TXT2TIF
    return TXT2TIF(iface)
